# Generated by Django 4.1.5 on 2023-10-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=20, verbose_name='it_name')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_api.account')),
            ],
        ),
    ]
